/**
 * Created by marcoazer on 15-09-10.
 */

/**
    Class Struct:
    {
        _id        : ID                 (INT Generated by MongoDB)
        name       : Class Name         (String)*
        stdtNum    : Number of Students (INT)
        srvntNum   : Number of Servants (INT)
        grade      : Class Grade        (Char(2))*
    }
*/

var collec = "class";

// Inserts

var InsertClass = function(db, cls, callback){
	db.collection(collec).insertOne(cls, function(err, data){
		assert.equal(null, err);
		console.log("Class was inserted properly");
		callback(data);
	});
}

var InsertClasses = function(db, clses, callback){
	db.collection(collec).insert(clses, function(err, data){
		assert.equal(null, err);
		console.log("Classes were inserted properly");
		callback(data);
	})
}