/**
  Student Struct:
    {
        _id        : ID                         (INT Generated by MongoDB)
        fname      : First name                 (String)*
        lname      : Last name                  (String)*
        mname      : Middle Name                (String)
        gender     : Gender                     (Char(1))*
        age        : Age                        (INT)*
        grade      : Grade                      (Char(2))*
        dob        : Date Of Birth              (Date)*
        phone      : Phone Number               (String)
        emergNum   : Emergency Contanct Number  (String)
        emergName  : Emergency Contanct Name    (String)
        addr       : Address                    (String)*
        pcode      : Postal Code                (String)
        curClassId : Current Class ID           (INT References Struct)*
        attendance : Dates attended             (Array of dates)
        outreach   : Dates outreached           (Array of dates)
    }
*/

var collec = 'student';

// Inserts

var InsertStudent = function(db, student, callback){
    db.collection(collec).insertOne(student, function(err, data){
        assert.equal(null, err);
        console.log('Student was inserted properly');
        callback(data);
    });
};

var InsertStudents = function(db, students, callback){
    db.collection(collec).insert(students, function(err, data){
        assert.equal(null, err);
        console.log('Students were inserted properly');
        callback(data);
    });
}

var InsertMname = function(db, id, mname, callback){
    db.collection(collec).updateOne(
        {"_id": id},
        {"mname": mname},
        function(err, data){
            assert.equal(null, err);
            console.log("Middle Name was inserted properly");
            callback(data);
        });
}

var InsertPhone = function(db, id, phone, callback){
    db.collection(collec).updateOne(
        {"_id": id},
        {"phone": phone},
        function(err, data){
            assert.equal(null, err);
            console.log("Phone was inserted properly");
            callback(data);
        });
}

var InsertEmergNum = function(db, id, emergnum, callback){
    db.collection(collec).updateOne(
        {"_id": id},
        {"emergNum": emergnum},
        function(err, data){
            assert.equal(null, err);
            console.log("Emergency Number was inserted properly");
            callback(data);
        });
}

var InsertEmergName = function(db, id, emergname, callback){
    db.collection(collec).updateOne(
        {"_id": id},
        {"emergName": emergname},
        function(err, data){
            assert.equal(null, err);
            console.log("Emergency Name was inserted properly");
            callback(data);
        });
}

var InsertPcode = function(db, id, pcode, callback){
    db.collection(collec).updateOne(
        {"_id": id},
        {"pcode": pcode},
        function(err, data){
            assert.equal(null, err);
            console.log("Postal Code was inserted properly");
            callback(data);
        });
}

var InsertAttendance = function(db, id, date, callback){
    db.collection(collec).updateOne(
        {"_id": id},
        {$push: {"attendance": date}},
        function(err, data){
            assert.equal(null, err);
            console.log("Attendance date was inserted properly");
            callback(data);
        }
    );
}

var InsetOutreach = function(db, id, date, callback){
    db.collection(collec).updateOne(
        {"_id":id},
        {$push: {"outreach": date}},
        function(err, data){
            assert.equal(null, err);
            console.log("Outreach date was inserted properly");
            callback(data);
        });
}

// Updates

var SetFname = function(db, id, fname, callback){
    db.collection(collec).updateOne(
        {"_id": id},
        {"fname": fname},
        function(err, data){
            assert.equal(null, err);
            console.log("First Name was set properly");
            callback(data);
        });
}

var SetLname = function(db, id, Lname, callback){
    db.collection(collec).updateOne(
        {"_id": id},
        {"lname": Lname},
        function(err, data){
            assert.equal(null, err);
            console.log("Last Name was set properly");
            callback(data);
        });
}

var SetGender = function(db, id, gender, callback){
    db.collection(collec).updateOne(
        {"_id": id},
        {"gender": gender},
        function(err, data){
            assert.equal(null, err);
            console.log("Gender was set properly");
            callback(data);
        });
}

var SetAge = function(db, id, age, callback){
    db.collection(collec).updateOne(
        {"_id": id},
        {"age": age},
        function(err, data){
            assert.equal(null, err);
            console.log("Age was set properly");
            callback(data);
        });
}

var SetGrade = function(db, id, grade, callback){
    db.collection(collec).updateOne(
        {"_id": id},
        {"grade": grade},
        function(err, data){
            assert.equal(null, err);
            console.log("Grade was set properly");
            callback(data);
        });
}

var SetDob = function(db, id, dob, callback){
    db.collection(collec).updateOne(
        {"_id": id},
        {"dob": dob},
        function(err, data){
            assert.equal(null, err);
            console.log("Day of birth was set properly");
            callback(data);
        });
}

var SetAddr = function(db, id, addr, callback){
    db.collection(collec).updateOne(
        {"_id": id},
        {"addr": addr},
        function(err, data){
            assert.equal(null, err);
            console.log("Address was set properly");
            callback(data);
        });
}

var SetClass = function(db, id, cid, callback){
    db.collection(collec).updateOne(
        {"_id": id},
        {"curClassId": cid},
        function(err, data){
            assert.equal(null, err);
            console.log("Class was set properly");
            callback(data);
        });
}